[features]
seeds = false
skip-lint = false
[programs.localnet]
calculator = "BF2NNM9nYT8f7CJq8wfDSFNADoECYg5p2u2KwHjEzdVW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/kenn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
